### ISSUE TITLE
Admin menu item not showing on non-multisite

### ISSUE THREAD

**Issue by felixarntz** [stuttter/wp-spider-cache#12]
By default I cannot see the admin menu item for the plugin on a non-multisite install, even though I am an admin.

This happens since admins do not have a `manage_cache` capability. Is this intended?
While this isn't a problem for super admins on a multisite, the capability is specifically required on non-multisite. The plugin currently does not add this capability nor uses `map_meta_cap()` to make it work. I wonder if this is intended (so that developers are responsible here) or an actual bug.

Btw, this is what I currently do on my setup to show the menu to specific administrators.

``` php
<?php
function map_cache_meta_cap_non_multisite( $caps, $cap, $user_id, $args ) {
  switch ( $cap ) {
    case 'manage_cache':
      if ( is_global_admin( $user_id ) ) { // this is a custom function on my setup (I define global admins in a constant)
        $caps = array( 'manage_options' );
      }
      break;
  }

  return $caps;
}
if ( ! is_multisite() ) {
    add_filter( 'map_meta_cap', 'map_cache_meta_cap_non_multisite', 10, 4 );
}
```

**Comment by kevinquinnyo** [comment]
I just tested this plugin tonight and noticed the same thing on a single-site setup.  My crass solution was just to add the `manage_cache` capability to my admin user.

Great plugin so far -- perfect for situations where you can't use something super aggressive like varnish.

**Comment by JJJ** [comment]
Fixed in https://github.com/stuttter/wp-spider-cache/commit/bb4d09d59ca152095e03a73dd64d19012aa32f9d

**Comment by kevinquinnyo** [comment]
:+1:

**Comment by kevinquinnyo** [comment]
When will this be pushed into the wordpress plugin svn?  I installed a recent version and it does not include this fix.  Should it?  This is the master branch right?

Just wondering because I'm thinking about using this in production, like very soon and I'd prefer not to have to git clone into my plugins dir if i can just install it normally.  Thanks!
