### ISSUE TITLE
Admin page not showing any results in the list

### ISSUE THREAD

**Issue by felixarntz** [stuttter/wp-spider-cache#13]
The list table on the admin page is not showing any results for me although object cache itself is working properly for me (I tested it by getting a specific post back from Memcached from a PHP script outside of WordPress; this worked correctly).

When I select the Memcached server, it makes an AJAX request, but an empty response is returned so that the table still stays empty.

I'm not sure what causes this, but I can provide any specific details as necessary. It's just right now I have no idea which details that may be since I'm not very familiar with Memcached.

**Comment by JJJ** [comment]
A few things to try:
- Check your web server logs for any missing methods or functions.
- In the latest master branch, the admin plugin _requires_ the use of the `object-cache.php` drop-in that comes with Spider Cache. Previous versions worked okay with others, but we were bottle-necked by them and created a few new functions of our own to help. We'll probably send them upstream to WordPress for consideration.
- Ensure your versions of Memcache and Memcached are up-to-date. Older versions do not have the `dump` function that the UI uses to retrieve all of the results.

**Comment by JJJ** [comment]
Hey @felixarntz, any updates here?

**Comment by felixarntz** [comment]
I haven't followed up on that issue, sorry. I had this problem on a test site (non-multisite) that doesn't exist any longer, as of now I'm only using the plugin on multisites, and it works correctly there (same server environment).

I can setup a regular site to check for that problem again if that helps.

**Comment by JJJ** [comment]
It's probably `Memcache` missing.

I added a notice if that's the case, but it's not very helpful. See #19.
