### ISSUE TITLE
memcache key collision with multiple wordpress instances on the same server?

### ISSUE THREAD

**Issue by kevinquinnyo** [stuttter/wp-spider-cache#14]
I'm seeing some weirdness -- one site loading the cached content of another, and it made me wonder if it's because this isn't currently designed for a "shared" server setup, in that more than one wordpress site could exist on the same server with the same memcached backend.

Am I right?

I quickly checked:

```
stats cachedump 1 100
ITEM wp_:comment_meta:1 [6 b; 1461811531 s]
ITEM wp_:post_meta:1 [6 b; 1461811531 s]
ITEM wp_:transient:is_multi_author [1 b; 1461811531 s]
ITEM wp_:default:is_blog_installed [1 b; 1461811531 s]
ITEM wp_:term_meta:1 [6 b; 1461811531 s]
ITEM wp_:userslugs:admin [1 b; 1461811531 s]
ITEM wp_:userlogins:admin [1 b; 1461811531 s]
```

And I see that the key is `wp_`.  Is there a way currently for that key to be configurable such that it's unique per site url?  I have not dug into the code yet, but I just wanted to throw this out and see if it's something you're aware of or if I'm even correct in my assumption.

Thanks!

**Comment by danielbachhuber** [comment]
You'll need to use `WP_CACHE_KEY_SALT` to set a unique salt for each install otherwise, as you've noticed, the data will collide.

**Comment by kevinquinnyo** [comment]
@danielbachhuber Doh!  Thanks.
