### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by bueltge** [stuttter/wp-spider-cache#20]
The readme.txt have no information about the changes to the current released version 2.2.1, I think it is helpful to add this. Followed also [here on wp.org](https://wordpress.org/plugins/wp-spider-cache/changelog/) no hint about this release.

Also I like a seprate `CHANGELOG.md` in the repository, maybe also a good idea for you? This file should use this formatting convention http://semver.org/

**Comment by JJJ** [comment]
Good suggestions.

The 2.2.1 version was just a bump to force WordPress.org to repackage the zip. There were no other changes.

And here I didn't think anyone was looking. :)

**Comment by lkraav** [comment]
> And here I didn't think anyone was looking. :)

Oh they are. When @bueltge sleeps, I take the shift over.

**Comment by bueltge** [comment]
@johnjamesjacoby I think it also a good idea to develop, release here, here is the first contact to the development. Maybe you add always a release tag and maybe also a `CHANGELOG.md`, the wp.org Repo should only a plattform for a released product. But it is your choice.

As example, also the last version, I'm confused.
- Published on wp.org is 3.0.0
- The [changelog on wp.org](https://wordpress.org/plugins/wp-spider-cache/changelog/) list version [3.0.10] - 2016-08-21
- Github repo have no tag, release for this version
- Also no changelog on github

**Comment by JJJ** [comment]
3.0.10 was a typo, corrected in 3.0.1 of all things.

**Comment by JJJ** [comment]
Changelog should be pretty well wrangled now. @bueltge - Please close if you think it's sufficient?

Thank you very much for the nudge!

**Comment by bueltge** [comment]
Really welcome!
