### ISSUE TITLE
Not working on wordpress 4.8

### ISSUE THREAD

**Issue by farridav** [stuttter/wp-spider-cache#26]
As soon as I copy the contents of the dropins to my wp-content, my site crashes, both in the admin, and on the frontend.

I realise the plugin has not yet been tested with 4.8, but I wanted to report it here first so you guys get the heads up.

Heres the error i receive in my logs:

```
2017/07/12 08:23:17 [error] 1350#1350: *55 FastCGI sent in stderr: 

"PHP message: PHP Fatal error:  Class 'Memcache' not found in /var/lib/wordpress/releases/current/wp-content/plugins/wp-spider-cache/wp-spider-cache/includes/base-object.php on line 246" while reading response header from upstream, client: 192.168.50.1, server: mydomain.com, request: "GET /wp-admin/admin.php?page=wp-spider-cache HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-memorabilia_framers.sock:", host: "mydomain.com", referrer: "https://mydomain.com/wp-admin/plugins.php"
```

And thanks for the great work on your plugin !

**Comment by JJJ** [comment]
Hey there! Sorry about this. Are you using the latest nightly from this repo, or the zip from WordPress.org? I think this should be fixed in `master` here.

**Comment by farridav** [comment]
Nice, I'll change my requirements, and keep an eye on the WordPress.org version

**Comment by JJJ** [comment]
👍 I hope to deploy to wporg early next week.
