### ISSUE TITLE
Feature request - Dynamic Version Salts

### ISSUE THREAD

**Issue by daigo75** [stuttter/wp-spider-cache#3]
## Problem

In many cases, a the content of a page may be different depending on the visitor who is looking at it (a typical example are ecommerce sites). Due to that, the assumption that one page = one cache key = one cached content doesn't work anymore. It's therefore necessary to be able to store multiple cached copies of a single page, depending on various criteria. The cache key can no longer by just the URL.
## Solution

Allowing to alter the cache key will make it possible to store multiple copies of cached content. Very useful feature, which should not be too complicated to implement by using advanced cache plugins. Here you can see how other plugins handle it:
- [ZenCache](http://zencache.com/kb-article/introduction-to-dynamic-version-salts/), see **Version Salts via "Advanced Cache Plugins"** section.
- [SuperCache](http://z9.io/wp-super-cache-developers/), see **Plugins** section.

From a quick look at the code, implementing the solution would involve the following:
- Add filters around cache keys (both the `url_key` and the result of `WP_Spider_Cache_Output::generate_keys()`). Custom caching modules will then hook into them.
- Add the logic to load custom modules. The approach used by ZenCache is the easiest. Using a custom folder outside the plugin's folder prevents the caching modules from being deleted when the plugin is updated. Loading the modules is as simple as including each PHP file found in that folder.

**Comment by JJJ** [comment]
The way to do this right now is with the `wp_output_cache_vary()` function.

We are having a conversation about improving it over in #1. I'll look at ZenCache's approach soon, and see if there's an inspiration there.

**Comment by JJJ** [comment]
@daigo75 Dropping by to let you know I haven't forgotten about this, and that I'm waiting to run into a use-case myself where I can prioritize it for you.

If you have any real-world examples of where the `wp_output_cache_vary()` function isn't providing the flexibility you desire, that might help me simplify the problem to better enable the functionality you desire.

**Comment by daigo75** [comment]
Please take your time. I didn't have the chance to test `wp_output_cache_vary()`, because I haven't come across an installation with Spider Cache, but it's in my to-do list. :+1:

**Comment by JJJ** [comment]
Coming back to confirm that `wp_output_cache_vary()` is right here, though I've imagined what might be a better way.

I'll close this for now, and make a new issue for the new way approach.
