### ISSUE TITLE
Not PHP 7.2 complient

### ISSUE THREAD

**Issue by thefrosty** [stuttter/wp-spider-cache#30]
Using `create_function` is deprecated in PHP 7.2. Found in `WP_Spider_Cache_Output::do_variants()`

**Comment by BrookeDot** [comment]
There is some more discussion about the plugin's use of `create_function` as well as a path forward for version 6.0 of the plugin in #1

**Comment by JJJ** [comment]
I've been using the callback approach for a while now, and it seems to work OK.

Added a `function_exists()` check to avoid fatals in PHP8.0 and above.
